### ISSUE TITLE
Add documentation link for hex

### ISSUE THREAD

**Issue by CrowdHailer** [potatosalad/erlang-libsodium#7]
Please.

If not I will try and contribute it later on, but as of now I don't know enough about rebar and am trying to make use of this library today.

**Comment by potatosalad** [comment]
@CrowdHailer Welp, several years later and the hex docs are now published here: https://hexdocs.pm/libsodium/, but they're semi-useless since I didn't typespec any of my functions.

This library is using the antiquated port driver pattern, is focused mostly on low-level libsodium access, and eventually needs to be rewritten as a NIF.  For most modern high-level use-cases, I'd recommend using [jlouis/enacl](https://github.com/jlouis/enacl) instead.
