### ISSUE TITLE
OTP 23 Not supported

### ISSUE THREAD

**Issue by dabaer** [potatosalad/erlang-libsodium#8]
Good day,

`erl_interface.h` was removed in OTP 23 causing compilation to fail

Looking at the examples for Erl_Interface I was able to get it working again by changing `libsodium_drv_common.h` to include <ei.h> instead, and removing `-lerl_interface` from the Makefile.

I'm not familiar with C or ports, so i'm unsure of the breadth of consequences of this, and would appreciate more experienced eyes on this.

One test currently fails but it's a function I don't use and am unfamiliar with: https://travis-ci.com/github/dabaer/erlang-libsodium/jobs/342993783

**Comment by talklittle** [comment]
Not familiar with this library but looked into this anyway. Couldn't reproduce the test failure you saw, on my local Docker, after making the 2 changes you indicated (Changing include to `<ei.h>` and removing `-lerl_interface`).

Therefore I assume it is okay to make these changes without negative impact on OTP 18-22 (assuming OTP 18 is minimum supported, since OTP 18.3 is the lowest version tested on Travis CI). And importantly fixes OTP 23+.

-----

Running the tests locally, using steps from the Travis configuration:

```
OTP_VERSION=18.3; docker build -t docker-otp-${OTP_VERSION} -f priv/Dockerfile --build-arg OTP_VERSION=${OTP_VERSION} priv;
OTP_VERSION=18.3; mkdir -p "docker-otp-${OTP_VERSION}"; docker save -o "docker-otp-${OTP_VERSION}/image.tar" docker-otp-${OTP_VERSION};
OTP_VERSION=18.3; docker run -v `pwd`:/build/libsodium docker-otp-${OTP_VERSION} sh -c 'cd libsodium && CC=clang-3.8 CXX=clang++-3.8 make tests'

OTP_VERSION=19.0; docker build -t docker-otp-${OTP_VERSION} -f priv/Dockerfile --build-arg OTP_VERSION=${OTP_VERSION} priv;
OTP_VERSION=19.0; mkdir -p "docker-otp-${OTP_VERSION}"; docker save -o "docker-otp-${OTP_VERSION}/image.tar" docker-otp-${OTP_VERSION};
OTP_VERSION=19.0; docker run -v `pwd`:/build/libsodium docker-otp-${OTP_VERSION} sh -c 'cd libsodium && CC=clang-3.8 CXX=clang++-3.8 make tests'
```

**Comment by michaelklishin** [comment]
#9 replaces `erl_interface.h` with `ei.h` as suggested by @dabaer 👍
